### ISSUE TITLE
Actualizar Dockerfile con los cambios:

### ISSUE THREAD

**Issue by alejandroalffer** [alastria/alastria-node-quorum#12]
- que esté basado en alpine/go-lang
- que use la version binaria de GoQuorum (21.10.x)

**Comment by alejandroalffer** [comment]
Qué tal van las pruebas? necesitas ayuda?

**Comment by dgonzalezmartin** [comment]
Me estaba dando un pequeño fallo al iniciarse el nodo. Para el martes lo tengo solucionado ;)

**Comment by dgonzalezmartin** [comment]
Buenas Alejandro dejé subida la versión de Alpine en la rama: https://github.com/alastria/alastria-node-quorum/tree/alpineRelease por si podéis echarle un ojo o cualquier cosa.
Si lo vais a mirar podéis llamarme y lo vemos juntos. 
Cualquier cosa ya sabéis. Un saludo!
