### ISSUE TITLE
Preguntas sobre este nuevo repositorio y contratos privados y testnet

### ISSUE THREAD

**Issue by tk-odoo** [alastria/alastria-node-quorum#32]
Hola buenas,

A ver si me podéis ayudar. Estoy tratando de montar un nodo con soporte para transacciones privadas utilizando los scripts de este repo. Hay cosas que no me quedan claras que en el archivado sí que puedo discernir:

1) Ni el README.md ni docker-compose de este repo no hace referencia al tema del Private Transaction Manager en la actualidad. Solamente aparece que el uso de Constellation ya no está soportado. Entonces, ¿qué se recomienda para el despliegue y utilización de contratos privados?

2) No logro hallar en este repo nada relacionado con el despliegue en la testnet de Red-T. ¿Cuál repo debo utilizar para ello si el alastria-node ha quedado deprecated y archivado?

**Comment by tk-odoo** [comment]
Gracias por tu pronta respuesta @irzinfante. Cuando comentas que no está soportada la configuración de transacciones privadas en Red-T, ¿esto significa que actualmente que no se puede utilizar en ésta o que simplemente los scripts proveídos por Alastria no lo habilitan? Y si es posible, ¿disponéis de algún recurso para configurarla?  Como recién llegado, me resultó confusa la parte del readme que menciona que Constellation ya no está soportado, ya que no entendí hasta que punto se pueden utilizar transacciones privadas en Red-T actualmente.

**Comment by irzinfante** [comment]
La configuración básica y necesaria presente en el repositorio no habilita el uso de transacciones privadas por defecto, pero no debería haber limitación para poder hacer uso de ellas. Las siguientes páginas y guías de Concensys pueden servirte de ayuda:

1. [Instalar Tessera](https://docs.tessera.consensys.net/en/stable/)
2. [Configurar un nodo con Tessera como private transaction manager](https://consensys.net/docs/goquorum/en/21.10.0/configure-and-manage/configure/private-transaction-manager/)
3. [Envío de transacciones privadas](https://consensys.net/docs/goquorum/en/21.10.0/tutorials/send-private-transaction/)

El uso, o no, de transacciones privadas es decisión propia de cada participante de la red.
