### ISSUE TITLE
Blocks generation stopped (11/12/2022)

### ISSUE THREAD

**Issue by irzinfante** [alastria/alastria-node-quorum#38]
Network has stopped generating blocks since 11/12/2022

The next steps are to create a private network between the validator nodes, make the network generate new blocks and then connect the rest of the nodes to the working network.

**Comment by alejandroalffer** [comment]
All consensus round validator nodes must:

* reach block 106983272
* update geth to version v1.9.25-stable-919800f0 (quorum-v21.10.0)

To do it:
* we can send you a cold copy of the DTL
* we can help in the migration process
* we can generate files of peers `permissioned-nodes.json` and `static-nodes.json` for each case

**Comment by irzinfante** [comment]
GoQuorum v21.10.2 preferred

**Comment by alejandroalffer** [comment]
> GoQuorum v21.10.2 preferred

Updated previus comment

**Comment by alejandroalffer** [comment]
Well...

> My nodes are not advancing in the chain to reach `106983272` block:

..going back one block on the DLT, the synchronization was rejoined. The DENIED-BY errors still remain:

```
> eth.blockNumber
106919851
> debug.setHead("0x65F77AA") 
null

$ docker restart

> eth.syncing
{
  currentBlock: 106934592,
  highestBlock: 106983272,
  knownStates: 12690992,
  pulledStates: 12690992,
  startingBlock: 106919850
}
```

We will evaluate this solution when all the validators are in block 106983272 and we have unified the version to 21.10.2

**Comment by alejandroalffer** [comment]
**VERY IMPORTANT**: It is highly recommended to run:

```
> debug.chains Compact()
```

Before running the debug.setHead() command

**Comment by hesusruiz** [comment]
I built a special version of Geth (Quorum 21.10.2) with logs to try to diagnose the problem with the Validators. I created a special repository: [alaquorum](https://github.com/hesusruiz/alaquorum).

The instructions for building the Geth executable are in the readme of the repository.

But the repo also contains an already build binary. For those using the official Dockerfile from the Alastria Node repository (this repo), they can easily switch to the patched Geth version by modifying the Dockerfile by replacing these lines:

```
RUN wget -O geth_${VER}_linux_amd64.tar.gz https://artifacts.consensys.net/public/go-quorum/raw/versions/${VER}/geth_${VER}_linux_amd64.tar.gz
RUN tar zxvf geth_${VER}_linux_amd64.tar.gz -C /usr/local/bin
```

with these:

```
RUN wget -O /usr/local/bin/geth https://raw.githubusercontent.com/hesusruiz/alaquorum/main/build/bin/geth
RUN chmod +x /usr/local/bin/geth
```

**Comment by alejandroalffer** [comment]
Opened issue with Consensus, in order to control the block number: most of the validator nodes cannot reach the desired:

https://github.com/ConsenSys/quorum/issues/1585

**Comment by alejandroalffer** [comment]
Added fix in https://github.com/alastria/alastria-node-quorum/pull/39 in order to start synchronization process

**Comment by alejandroalffer** [comment]
The network is operational again, thanks to the corrective actions in:

- https://github.com/hesusruiz/alaquorum
- https://github.com/hesusruiz/RedTValidatorNode

Still pending to unify blocks and (patched) versions of @JesusRuiz but transactions are being mined
